name: "Build ServicePool"
on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
    branches-ignore:
      - 'docs*'
    tags-ignore:
      - '*'
jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: src/ServicePool.sln
      Configuration: Debug
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build and test ServicePool
      run: dotnet test $env:Solution_Name --configuration=$env:Configuration --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
    - name: Upload code coverage report
      run: codecov -f "$((ls .\src\ServicePool.Tests\TestResults -Directory)[0].Fullname)\coverage.opencover.xml"
    - name: Create NuGet Packages
      run: dotnet pack $env:Solution_Name --configuration=$env:Configuration --version-suffix=$env:GITHUB_SHA --include-source -p:RepositoryBranch=${{ github.ref }} -p:ContinuousIntegrationBuild=true
    - uses: actions/upload-artifact@v2
      with:
        name: ServicePool-nuget-packages
        path: Build/Bin/**/*.nupkg
